name: Daily Script

on:
  workflow_dispatch:
# on: 
#   schedule:
#     - cron: "0 13 * * *" # Runs at 1AM UTC everyday

jobs:
  test: 
    runs-on: ubuntu-latest
  
    steps:
    - name: Run Cypress tests
      run: |
        npx cypress run
        
    - name: Merge mochawesome reports 
      run: |
        npx mochawesome-merge "cypress/results/*.json" > mochawesome.json
          
    - name: Run encode.js  
      run: node encode.js
    
    - name: Generate mochawesome report
      run: npx mochawesome-report-generator mochawesome.json
        
    - name: Upload mochawesome report  
      uses: actions/upload-artifact@v3
      with:
        name: mochawesome-report
        path: mochawesome-report
              
    - name: Commit updated report
      run: |  
            git config --global user.name ariel.lin
            git config --global user.email ariel.lin@ecpay.com.tw
            git add .
            git commit -m "Daily update report"
            git pull origin master
            git push
