name: Docker Image CI

on:
  push:
    branches: [master]
  schedule:
      - cron: '1 0 * * 1-5'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login --username=arielin024 --password=${{ secrets.ARIELIN024 }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: arielin024/my-image:latest
