name: Build and Test 

on:
  push:
    branches:
     - master
  pull_request:
    branches:  
     - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2

    - name: Check Dockerfile
      run: |
        test -f Dockerfile || echo "No Dockerfile found." && exit 1

    - name: Pull Docker image  
      run: docker pull cypress/included:10.3.0

    - name: Build Docker image
      run: docker build . --file Dockerfile --tag my-cypress-image

    - name: Run Cypress tests
      uses: nick-invision/retry@v2
      with:
        timeout_minutes: 5
        max_attempts: 3
        command: |
          docker run -v ${{ github.workspace }}:/app my-cypress-image
          docker cp my-cypress-image:/app/cypress/results/.jsons ./cypress/results

    - name: Upload results artifact  
      uses: actions/upload-artifact@master
      timeout-minutes: 5  
      with:
       name: cypress-results
       path: cypress/results
       if-no-files-found: ignore
